---@class ExalityUI
local EXUI = select(2, ...)

---@class EXUIUnitFramesAurasDefaults
local defaults = EXUI:GetModule('uf-auras-defaults')

-- One-time starter aura displays. Seeded into a profile once; never re-applied after delete.
defaults.STARTER_DISPLAYS = {
["ovrdAkmVGBtm"] = {
    ["horizontalGrowth"] = "LEFT",
    ["enable"] = true,
    ["containerAnchorPoint"] = "TOPRIGHT",
    ["anchorPoint"] = "TOPRIGHT",
    ["createdAt"] = 1784216437,
    ["groups"] = {
        ["0ag19ugsZiLb"] = {
            ["enable"] = true,
            ["conditions"] = {
                ["isPriorityAura"] = false,
                ["isBossAura"] = false,
                ["isStealable"] = false,
                ["isFromPlayerOrPlayerPet"] = false,
                ["isRoleAura"] = false,
                ["sortDirection"] = "Normal",
                ["filterTokens"] = {
                    {
                        ["token"] = "HARMFUL",
                        ["negated"] = false,
                    },
                    {
                        ["token"] = "PLAYER",
                        ["negated"] = false,
                    },
                },
                ["nameplateShowPersonal"] = false,
                ["nameplateShowAll"] = false,
                ["isBossOrRoleAura"] = false,
                ["includeSpellIDs"] = "",
                ["excludeSpellIDs"] = "",
                ["maxDuration"] = 0,
                ["includeDispelTypes"] = {
                },
                ["canApplyAura"] = false,
                ["sortMethod"] = "Default",
                ["enable"] = true,
                ["groupType"] = "group",
                ["excludeDispelTypes"] = {
                },
                ["maxFrameCount"] = 4,
            },
            ["load"] = {
                ["loadRoles"] = {
                },
                ["loadSpecs"] = {
                },
                ["loadInstances"] = {
                },
                ["hasLoadConditions"] = false,
                ["onlyLoadOnPlayer"] = "",
                ["loadClasses"] = {
                },
                ["dontLoadOnPlayer"] = "",
            },
            ["visual"] = {
                ["durationColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["barIconPosition"] = "LEFT",
                ["durationFormat"] = "mmss",
                ["barBorderThickness"] = 1,
                ["spellNameYOff"] = -2,
                ["stackRelativePoint"] = "BOTTOMRIGHT",
                ["elementHeight"] = 0,
                ["elementWidth"] = 0,
                ["showStacks"] = true,
                ["iconWidth"] = 40,
                ["barTexture"] = "ExalityUI Status Bar",
                ["barColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 0.6,
                    ["r"] = 0.2,
                },
                ["stackFontSize"] = 12,
                ["barBorderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["slotRelativePoint"] = "CENTER",
                ["stackFont"] = "DMSans",
                ["slotAnchorPoint"] = "CENTER",
                ["slotYOff"] = 0,
                ["showDurationText"] = true,
                ["dispelBorderShowIcon"] = true,
                ["displayStyle"] = "icon",
                ["gapY"] = 0,
                ["durationExpiredText"] = "",
                ["barTimerDirection"] = "RemainingTime",
                ["barIconGap"] = 0,
                ["elementSpacingY"] = 2,
                ["gapX"] = 0,
                ["stackColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["spellNameFontSize"] = 10,
                ["durationYOff"] = 0,
                ["slotXOff"] = 0,
                ["dispelBorderStyle"] = "Atlas",
                ["stackAnchorPoint"] = "BOTTOMRIGHT",
                ["durationZeroText"] = "",
                ["showSpellName"] = false,
                ["durationFontFlag"] = "OUTLINE",
                ["spellNameAnchorPoint"] = "BOTTOM",
                ["dispelBorderHarmful"] = true,
                ["spellNameRelativePoint"] = "TOP",
                ["iconBorderThickness"] = 1,
                ["barBackgroundColor"] = {
                    ["a"] = 0.5,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["durationFontSize"] = 12,
                ["showBarIcon"] = true,
                ["durationAnchorPoint"] = "CENTER",
                ["stackFontFlag"] = "OUTLINE",
                ["spellNameXOff"] = 0,
                ["dispelBorderHelpful"] = false,
                ["spellNameColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["spellNameFontFlag"] = "OUTLINE",
                ["spellNameFont"] = "DMSans",
                ["showDurationCooldown"] = true,
                ["durationUpdateInterval"] = 0,
                ["iconHeight"] = 40,
                ["iconBorderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["showDispelBorder"] = true,
                ["durationXOff"] = 0,
                ["durationRelativePoint"] = "CENTER",
                ["durationFont"] = "DMSans",
                ["forceNewRow"] = false,
                ["showIconBorder"] = true,
                ["iconZoom"] = 14,
                ["barHeight"] = 20,
                ["stackXOff"] = -2,
                ["elementSpacingX"] = 2,
                ["stackYOff"] = 2,
                ["barWidth"] = 160,
            },
        },
    },
    ["relativePoint"] = "TOPLEFT",
    ["paddingBottom"] = 0,
    ["container"] = {
        ["itemEnchantWidth"] = 0,
        ["itemEnchantPlacement"] = "BeforeAuraGroups",
        ["itemEnchantRanged"] = false,
        ["itemEnchantHidePermanent"] = false,
        ["itemEnchantSpacingX"] = 2,
        ["itemEnchantHeight"] = 0,
        ["itemEnchantGapY"] = 0,
        ["itemEnchantEnable"] = false,
        ["itemEnchantGapX"] = 0,
        ["processAuraOptions"] = {
            ["ignoreDebuffs"] = false,
            ["ignoreDispelDebuffs"] = false,
            ["displayOnlyDispellableDebuffs"] = false,
            ["ignoreBuffs"] = false,
        },
        ["itemEnchantMainHand"] = false,
        ["itemEnchantSpacingY"] = 2,
        ["itemEnchantOffHand"] = false,
    },
    ["paddingTop"] = 0,
    ["frameLevel"] = 10,
    ["matchUnitFrameWidth"] = true,
    ["frameStrata"] = "LOW",
    ["units"] = {
        ["boss"] = true,
    },
    ["rowWidth"] = 200,
    ["verticalGrowth"] = "UP",
    ["name"] = "My Debuffs",
    ["XOff"] = 0,
    ["paddingRight"] = 0,
    ["YOff"] = 0,
    ["paddingLeft"] = 0,
    ["groupOrder"] = {
        "0ag19ugsZiLb",
    },
},
["BLoOUKQtTR7A"] = {
    ["horizontalGrowth"] = "RIGHT",
    ["enable"] = true,
    ["containerAnchorPoint"] = "TOPLEFT",
    ["anchorPoint"] = "TOPLEFT",
    ["createdAt"] = 1784216848,
    ["groups"] = {
        ["ZsOZ8OAdfjPM"] = {
            ["enable"] = true,
            ["conditions"] = {
                ["isPriorityAura"] = false,
                ["isBossAura"] = false,
                ["isStealable"] = false,
                ["isFromPlayerOrPlayerPet"] = false,
                ["isRoleAura"] = false,
                ["sortDirection"] = "Normal",
                ["filterTokens"] = {
                    {
                        ["token"] = "HARMFUL",
                        ["negated"] = false,
                    },
                    {
                        ["token"] = "RAID_IN_COMBAT",
                        ["negated"] = false,
                    },
                },
                ["nameplateShowPersonal"] = false,
                ["nameplateShowAll"] = false,
                ["isBossOrRoleAura"] = false,
                ["includeSpellIDs"] = "",
                ["excludeSpellIDs"] = "",
                ["maxDuration"] = 0,
                ["includeDispelTypes"] = {
                },
                ["canApplyAura"] = false,
                ["sortMethod"] = "Default",
                ["enable"] = true,
                ["groupType"] = "group",
                ["excludeDispelTypes"] = {
                },
                ["maxFrameCount"] = 4,
            },
            ["load"] = {
                ["loadRoles"] = {
                },
                ["loadSpecs"] = {
                },
                ["loadInstances"] = {
                },
                ["hasLoadConditions"] = false,
                ["onlyLoadOnPlayer"] = "",
                ["loadClasses"] = {
                },
                ["dontLoadOnPlayer"] = "",
            },
            ["visual"] = {
                ["durationColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["barIconPosition"] = "LEFT",
                ["durationFormat"] = "mmss",
                ["barBorderThickness"] = 1,
                ["spellNameYOff"] = -2,
                ["stackRelativePoint"] = "TOPRIGHT",
                ["elementHeight"] = 0,
                ["elementWidth"] = 0,
                ["showStacks"] = true,
                ["iconWidth"] = 23,
                ["barTexture"] = "ExalityUI Status Bar",
                ["barColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 0.6,
                    ["r"] = 0.2,
                },
                ["stackFontSize"] = 13,
                ["barBorderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["slotRelativePoint"] = "CENTER",
                ["stackFont"] = "DMSans",
                ["slotAnchorPoint"] = "CENTER",
                ["slotYOff"] = 0,
                ["showDurationText"] = true,
                ["dispelBorderShowIcon"] = true,
                ["displayStyle"] = "icon",
                ["gapY"] = 0,
                ["durationExpiredText"] = "",
                ["barTimerDirection"] = "RemainingTime",
                ["barIconGap"] = 0,
                ["elementSpacingY"] = 2,
                ["gapX"] = 0,
                ["stackColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["spellNameFontSize"] = 10,
                ["durationYOff"] = 1,
                ["slotXOff"] = 0,
                ["dispelBorderStyle"] = "Atlas",
                ["stackAnchorPoint"] = "RIGHT",
                ["durationZeroText"] = "",
                ["showSpellName"] = false,
                ["durationFontFlag"] = "OUTLINE",
                ["spellNameAnchorPoint"] = "BOTTOM",
                ["dispelBorderHarmful"] = true,
                ["spellNameRelativePoint"] = "TOP",
                ["iconBorderThickness"] = 1,
                ["barBackgroundColor"] = {
                    ["a"] = 0.5,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["durationFontSize"] = 12,
                ["showBarIcon"] = true,
                ["durationAnchorPoint"] = "BOTTOMLEFT",
                ["stackFontFlag"] = "OUTLINE",
                ["spellNameXOff"] = 0,
                ["dispelBorderHelpful"] = false,
                ["spellNameColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["spellNameFontFlag"] = "OUTLINE",
                ["spellNameFont"] = "DMSans",
                ["showDurationCooldown"] = true,
                ["durationUpdateInterval"] = 0,
                ["iconHeight"] = 23,
                ["iconBorderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["showDispelBorder"] = true,
                ["durationXOff"] = 1,
                ["durationRelativePoint"] = "BOTTOMLEFT",
                ["durationFont"] = "DMSans",
                ["forceNewRow"] = false,
                ["showIconBorder"] = true,
                ["iconZoom"] = 14,
                ["barHeight"] = 20,
                ["stackXOff"] = 0,
                ["elementSpacingX"] = 2,
                ["stackYOff"] = -1,
                ["barWidth"] = 160,
            },
        },
        ["AubbaVuMhtDN"] = {
            ["enable"] = true,
            ["conditions"] = {
                ["isPriorityAura"] = false,
                ["isBossAura"] = false,
                ["isStealable"] = false,
                ["isFromPlayerOrPlayerPet"] = false,
                ["isRoleAura"] = false,
                ["sortDirection"] = "Normal",
                ["filterTokens"] = {
                    {
                        ["token"] = "HARMFUL",
                        ["negated"] = false,
                    },
                    {
                        ["token"] = "IMPORTANT",
                        ["negated"] = false,
                    },
                },
                ["nameplateShowPersonal"] = false,
                ["nameplateShowAll"] = false,
                ["isBossOrRoleAura"] = false,
                ["includeSpellIDs"] = "",
                ["maxFrameCount"] = 4,
                ["maxDuration"] = 0,
                ["includeDispelTypes"] = {
                },
                ["canApplyAura"] = false,
                ["sortMethod"] = "Default",
                ["enable"] = true,
                ["groupType"] = "group",
                ["excludeDispelTypes"] = {
                },
                ["excludeSpellIDs"] = "",
            },
            ["load"] = {
                ["loadRoles"] = {
                },
                ["loadSpecs"] = {
                },
                ["loadInstances"] = {
                },
                ["hasLoadConditions"] = false,
                ["onlyLoadOnPlayer"] = "",
                ["loadClasses"] = {
                },
                ["dontLoadOnPlayer"] = "",
            },
            ["visual"] = {
                ["durationColor"] = {
                    ["a"] = 1,
                    ["r"] = 1,
                    ["g"] = 1,
                    ["b"] = 1,
                },
                ["barIconPosition"] = "LEFT",
                ["durationFormat"] = "mmss",
                ["barHeight"] = 20,
                ["spellNameYOff"] = -2,
                ["stackRelativePoint"] = "TOPRIGHT",
                ["elementHeight"] = 0,
                ["elementWidth"] = 0,
                ["showStacks"] = true,
                ["iconWidth"] = 23,
                ["barTexture"] = "ExalityUI Status Bar",
                ["barColor"] = {
                    ["a"] = 1,
                    ["r"] = 0.2,
                    ["g"] = 0.6,
                    ["b"] = 1,
                },
                ["stackFontSize"] = 13,
                ["barBorderColor"] = {
                    ["a"] = 1,
                    ["r"] = 0,
                    ["g"] = 0,
                    ["b"] = 0,
                },
                ["slotRelativePoint"] = "CENTER",
                ["stackFont"] = "DMSans",
                ["slotAnchorPoint"] = "CENTER",
                ["slotYOff"] = 0,
                ["showDurationText"] = true,
                ["dispelBorderShowIcon"] = true,
                ["displayStyle"] = "icon",
                ["gapY"] = 0,
                ["durationExpiredText"] = "",
                ["barTimerDirection"] = "RemainingTime",
                ["barIconGap"] = 0,
                ["elementSpacingY"] = 2,
                ["gapX"] = 0,
                ["stackColor"] = {
                    ["a"] = 1,
                    ["r"] = 1,
                    ["g"] = 1,
                    ["b"] = 1,
                },
                ["spellNameFontSize"] = 10,
                ["forceNewRow"] = false,
                ["slotXOff"] = 0,
                ["dispelBorderStyle"] = "Atlas",
                ["stackAnchorPoint"] = "RIGHT",
                ["durationZeroText"] = "",
                ["showSpellName"] = false,
                ["durationFontFlag"] = "OUTLINE",
                ["iconBorderColor"] = {
                    ["a"] = 1,
                    ["r"] = 0,
                    ["g"] = 0,
                    ["b"] = 0,
                },
                ["spellNameFontFlag"] = "OUTLINE",
                ["spellNameRelativePoint"] = "TOP",
                ["iconBorderThickness"] = 1,
                ["barBackgroundColor"] = {
                    ["a"] = 0.5,
                    ["r"] = 0,
                    ["g"] = 0,
                    ["b"] = 0,
                },
                ["durationFontSize"] = 12,
                ["showBarIcon"] = true,
                ["durationAnchorPoint"] = "BOTTOMLEFT",
                ["stackFontFlag"] = "OUTLINE",
                ["spellNameXOff"] = 0,
                ["stackYOff"] = -1,
                ["elementSpacingX"] = 2,
                ["stackXOff"] = 0,
                ["barBorderThickness"] = 1,
                ["iconHeight"] = 23,
                ["showIconBorder"] = true,
                ["durationYOff"] = 1,
                ["durationFont"] = "DMSans",
                ["showDispelBorder"] = true,
                ["durationRelativePoint"] = "BOTTOMLEFT",
                ["spellNameAnchorPoint"] = "BOTTOM",
                ["durationXOff"] = 1,
                ["dispelBorderHarmful"] = true,
                ["durationUpdateInterval"] = 0,
                ["iconZoom"] = 14,
                ["showDurationCooldown"] = true,
                ["spellNameFont"] = "DMSans",
                ["spellNameColor"] = {
                    ["a"] = 1,
                    ["r"] = 1,
                    ["g"] = 1,
                    ["b"] = 1,
                },
                ["dispelBorderHelpful"] = false,
                ["barWidth"] = 160,
            },
        },
    },
    ["relativePoint"] = "TOPLEFT",
    ["paddingBottom"] = 0,
    ["container"] = {
        ["itemEnchantWidth"] = 0,
        ["itemEnchantPlacement"] = "BeforeAuraGroups",
        ["itemEnchantRanged"] = false,
        ["itemEnchantHidePermanent"] = false,
        ["itemEnchantSpacingX"] = 2,
        ["itemEnchantHeight"] = 0,
        ["itemEnchantGapY"] = 0,
        ["itemEnchantEnable"] = false,
        ["itemEnchantGapX"] = 0,
        ["processAuraOptions"] = {
            ["ignoreDebuffs"] = false,
            ["ignoreDispelDebuffs"] = false,
            ["displayOnlyDispellableDebuffs"] = false,
            ["ignoreBuffs"] = false,
        },
        ["itemEnchantMainHand"] = false,
        ["itemEnchantSpacingY"] = 2,
        ["itemEnchantOffHand"] = false,
    },
    ["paddingTop"] = 0,
    ["frameLevel"] = 10,
    ["matchUnitFrameWidth"] = true,
    ["frameStrata"] = "LOW",
    ["units"] = {
        ["raid"] = true,
        ["party"] = true,
    },
    ["rowWidth"] = 200,
    ["verticalGrowth"] = "UP",
    ["name"] = "Important Debuffs",
    ["XOff"] = 2,
    ["paddingRight"] = 0,
    ["YOff"] = -2,
    ["paddingLeft"] = 0,
    ["groupOrder"] = {
        "ZsOZ8OAdfjPM",
        "AubbaVuMhtDN",
    },
},
["vtUbMyGA3dZ4"] = {
    ["horizontalGrowth"] = "RIGHT",
    ["enable"] = true,
    ["containerAnchorPoint"] = "TOPLEFT",
    ["anchorPoint"] = "TOPLEFT",
    ["createdAt"] = 1784216555,
    ["groups"] = {
        ["kYH9mTCuXY7d"] = {
            ["enable"] = true,
            ["conditions"] = {
                ["isPriorityAura"] = false,
                ["isBossAura"] = false,
                ["isStealable"] = false,
                ["isFromPlayerOrPlayerPet"] = false,
                ["isRoleAura"] = false,
                ["sortDirection"] = "Normal",
                ["filterTokens"] = {
                    {
                        ["token"] = "HELPFUL",
                        ["negated"] = false,
                    },
                    {
                        ["token"] = "PLAYER",
                        ["negated"] = true,
                    },
                    {
                        ["token"] = "RAID_IN_COMBAT",
                        ["negated"] = false,
                    },
                },
                ["nameplateShowPersonal"] = false,
                ["nameplateShowAll"] = false,
                ["isBossOrRoleAura"] = false,
                ["includeSpellIDs"] = "",
                ["maxFrameCount"] = 4,
                ["maxDuration"] = 0,
                ["includeDispelTypes"] = {
                },
                ["canApplyAura"] = false,
                ["sortMethod"] = "Default",
                ["enable"] = true,
                ["groupType"] = "group",
                ["excludeDispelTypes"] = {
                },
                ["excludeSpellIDs"] = "",
            },
            ["load"] = {
                ["loadRoles"] = {
                },
                ["loadSpecs"] = {
                },
                ["loadInstances"] = {
                },
                ["hasLoadConditions"] = false,
                ["onlyLoadOnPlayer"] = "",
                ["loadClasses"] = {
                },
                ["dontLoadOnPlayer"] = "",
            },
            ["visual"] = {
                ["durationColor"] = {
                    ["a"] = 1,
                    ["r"] = 1,
                    ["g"] = 1,
                    ["b"] = 1,
                },
                ["barIconPosition"] = "LEFT",
                ["durationFormat"] = "mmss",
                ["barHeight"] = 20,
                ["spellNameYOff"] = -2,
                ["stackRelativePoint"] = "BOTTOMRIGHT",
                ["elementHeight"] = 0,
                ["elementWidth"] = 0,
                ["showStacks"] = true,
                ["iconWidth"] = 40,
                ["barTexture"] = "ExalityUI Status Bar",
                ["barColor"] = {
                    ["a"] = 1,
                    ["r"] = 0.2,
                    ["g"] = 0.6,
                    ["b"] = 1,
                },
                ["stackFontSize"] = 12,
                ["barBorderColor"] = {
                    ["a"] = 1,
                    ["r"] = 0,
                    ["g"] = 0,
                    ["b"] = 0,
                },
                ["slotRelativePoint"] = "CENTER",
                ["stackXOff"] = -2,
                ["slotAnchorPoint"] = "CENTER",
                ["slotYOff"] = 0,
                ["showDurationText"] = true,
                ["dispelBorderShowIcon"] = true,
                ["displayStyle"] = "icon",
                ["gapY"] = 0,
                ["durationExpiredText"] = "",
                ["barTimerDirection"] = "RemainingTime",
                ["barIconGap"] = 0,
                ["elementSpacingY"] = 2,
                ["gapX"] = 0,
                ["stackColor"] = {
                    ["a"] = 1,
                    ["r"] = 1,
                    ["g"] = 1,
                    ["b"] = 1,
                },
                ["spellNameFontSize"] = 10,
                ["forceNewRow"] = false,
                ["slotXOff"] = 0,
                ["dispelBorderStyle"] = "Atlas",
                ["stackAnchorPoint"] = "BOTTOMRIGHT",
                ["durationZeroText"] = "",
                ["showSpellName"] = false,
                ["durationFontFlag"] = "OUTLINE",
                ["spellNameAnchorPoint"] = "BOTTOM",
                ["dispelBorderHarmful"] = true,
                ["spellNameRelativePoint"] = "TOP",
                ["iconBorderThickness"] = 1,
                ["barBackgroundColor"] = {
                    ["a"] = 0.5,
                    ["r"] = 0,
                    ["g"] = 0,
                    ["b"] = 0,
                },
                ["durationFontSize"] = 12,
                ["showBarIcon"] = true,
                ["durationAnchorPoint"] = "CENTER",
                ["stackFontFlag"] = "OUTLINE",
                ["spellNameXOff"] = 0,
                ["stackYOff"] = 2,
                ["elementSpacingX"] = 2,
                ["showDurationCooldown"] = true,
                ["stackFont"] = "DMSans",
                ["spellNameFont"] = "DMSans",
                ["showIconBorder"] = true,
                ["durationRelativePoint"] = "CENTER",
                ["durationXOff"] = 0,
                ["showDispelBorder"] = true,
                ["iconBorderColor"] = {
                    ["a"] = 1,
                    ["r"] = 0,
                    ["g"] = 0,
                    ["b"] = 0,
                },
                ["iconHeight"] = 40,
                ["durationFont"] = "DMSans",
                ["durationYOff"] = 0,
                ["durationUpdateInterval"] = 0,
                ["iconZoom"] = 14,
                ["barBorderThickness"] = 1,
                ["spellNameFontFlag"] = "OUTLINE",
                ["spellNameColor"] = {
                    ["a"] = 1,
                    ["r"] = 1,
                    ["g"] = 1,
                    ["b"] = 1,
                },
                ["dispelBorderHelpful"] = false,
                ["barWidth"] = 160,
            },
        },
        ["HDrwvhPLwVw4"] = {
            ["enable"] = true,
            ["conditions"] = {
                ["isPriorityAura"] = false,
                ["isBossAura"] = false,
                ["isStealable"] = false,
                ["isFromPlayerOrPlayerPet"] = false,
                ["isRoleAura"] = false,
                ["sortDirection"] = "Normal",
                ["filterTokens"] = {
                    {
                        ["token"] = "HELPFUL",
                        ["negated"] = false,
                    },
                    {
                        ["token"] = "PLAYER",
                        ["negated"] = true,
                    },
                    {
                        ["token"] = "IMPORTANT",
                        ["negated"] = false,
                    },
                },
                ["nameplateShowPersonal"] = false,
                ["nameplateShowAll"] = false,
                ["isBossOrRoleAura"] = false,
                ["includeSpellIDs"] = "",
                ["excludeSpellIDs"] = "",
                ["maxDuration"] = 0,
                ["includeDispelTypes"] = {
                },
                ["canApplyAura"] = false,
                ["sortMethod"] = "Default",
                ["enable"] = true,
                ["groupType"] = "group",
                ["excludeDispelTypes"] = {
                },
                ["maxFrameCount"] = 4,
            },
            ["load"] = {
                ["loadRoles"] = {
                },
                ["loadSpecs"] = {
                },
                ["loadInstances"] = {
                },
                ["hasLoadConditions"] = false,
                ["onlyLoadOnPlayer"] = "",
                ["loadClasses"] = {
                },
                ["dontLoadOnPlayer"] = "",
            },
            ["visual"] = {
                ["durationColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["barIconPosition"] = "LEFT",
                ["durationFormat"] = "mmss",
                ["barBorderThickness"] = 1,
                ["spellNameYOff"] = -2,
                ["stackRelativePoint"] = "BOTTOMRIGHT",
                ["elementHeight"] = 0,
                ["elementWidth"] = 0,
                ["showStacks"] = true,
                ["iconWidth"] = 40,
                ["barTexture"] = "ExalityUI Status Bar",
                ["barColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 0.6,
                    ["r"] = 0.2,
                },
                ["stackFontSize"] = 12,
                ["barBorderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["slotRelativePoint"] = "CENTER",
                ["stackFont"] = "DMSans",
                ["slotAnchorPoint"] = "CENTER",
                ["slotYOff"] = 0,
                ["showDurationText"] = true,
                ["dispelBorderShowIcon"] = true,
                ["displayStyle"] = "icon",
                ["gapY"] = 0,
                ["durationExpiredText"] = "",
                ["barTimerDirection"] = "RemainingTime",
                ["barIconGap"] = 0,
                ["elementSpacingY"] = 2,
                ["gapX"] = 0,
                ["stackColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["spellNameFontSize"] = 10,
                ["durationYOff"] = 0,
                ["slotXOff"] = 0,
                ["dispelBorderStyle"] = "Atlas",
                ["stackAnchorPoint"] = "BOTTOMRIGHT",
                ["durationZeroText"] = "",
                ["showSpellName"] = false,
                ["durationFontFlag"] = "OUTLINE",
                ["iconBorderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["dispelBorderHarmful"] = true,
                ["spellNameRelativePoint"] = "TOP",
                ["iconBorderThickness"] = 1,
                ["barBackgroundColor"] = {
                    ["a"] = 0.5,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["durationFontSize"] = 12,
                ["showBarIcon"] = true,
                ["durationAnchorPoint"] = "CENTER",
                ["stackFontFlag"] = "OUTLINE",
                ["spellNameXOff"] = 0,
                ["dispelBorderHelpful"] = false,
                ["spellNameColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["spellNameFontFlag"] = "OUTLINE",
                ["barHeight"] = 20,
                ["stackXOff"] = -2,
                ["durationUpdateInterval"] = 0,
                ["forceNewRow"] = false,
                ["durationFont"] = "DMSans",
                ["showDispelBorder"] = true,
                ["iconHeight"] = 40,
                ["spellNameAnchorPoint"] = "BOTTOM",
                ["durationXOff"] = 0,
                ["durationRelativePoint"] = "CENTER",
                ["showIconBorder"] = true,
                ["iconZoom"] = 14,
                ["spellNameFont"] = "DMSans",
                ["showDurationCooldown"] = true,
                ["elementSpacingX"] = 2,
                ["stackYOff"] = 2,
                ["barWidth"] = 160,
            },
        },
    },
    ["relativePoint"] = "TOPRIGHT",
    ["paddingBottom"] = 0,
    ["container"] = {
        ["itemEnchantWidth"] = 0,
        ["itemEnchantPlacement"] = "BeforeAuraGroups",
        ["itemEnchantRanged"] = false,
        ["itemEnchantHidePermanent"] = false,
        ["itemEnchantSpacingX"] = 2,
        ["itemEnchantOffHand"] = false,
        ["itemEnchantEnable"] = false,
        ["itemEnchantGapY"] = 0,
        ["itemEnchantGapX"] = 0,
        ["processAuraOptions"] = {
            ["ignoreDebuffs"] = false,
            ["ignoreDispelDebuffs"] = false,
            ["displayOnlyDispellableDebuffs"] = false,
            ["ignoreBuffs"] = false,
        },
        ["itemEnchantMainHand"] = false,
        ["itemEnchantSpacingY"] = 2,
        ["itemEnchantHeight"] = 0,
    },
    ["paddingTop"] = 0,
    ["frameLevel"] = 10,
    ["matchUnitFrameWidth"] = true,
    ["frameStrata"] = "LOW",
    ["units"] = {
        ["boss"] = true,
    },
    ["rowWidth"] = 200,
    ["verticalGrowth"] = "UP",
    ["name"] = "Boss Buffs",
    ["groupOrder"] = {
        "kYH9mTCuXY7d",
        "HDrwvhPLwVw4",
    },
    ["paddingLeft"] = 0,
    ["YOff"] = 0,
    ["paddingRight"] = 0,
    ["XOff"] = 0,
},
["Nc98r9ZJFlfk"] = {
    ["horizontalGrowth"] = "RIGHT",
    ["enable"] = true,
    ["containerAnchorPoint"] = "BOTTOMLEFT",
    ["anchorPoint"] = "BOTTOMLEFT",
    ["createdAt"] = 1784139602,
    ["groups"] = {
        ["1gyg5a6uJjVv"] = {
            ["enable"] = true,
            ["conditions"] = {
                ["isPriorityAura"] = false,
                ["isBossAura"] = false,
                ["isStealable"] = false,
                ["isFromPlayerOrPlayerPet"] = false,
                ["isRoleAura"] = false,
                ["sortDirection"] = "Normal",
                ["filterTokens"] = {
                    {
                        ["token"] = "HARMFUL",
                        ["negated"] = false,
                    },
                    {
                        ["token"] = "PLAYER",
                        ["negated"] = false,
                    },
                },
                ["nameplateShowPersonal"] = false,
                ["nameplateShowAll"] = false,
                ["isBossOrRoleAura"] = false,
                ["includeSpellIDs"] = "",
                ["maxFrameCount"] = 10,
                ["maxDuration"] = 0,
                ["includeDispelTypes"] = {
                },
                ["canApplyAura"] = false,
                ["sortMethod"] = "Default",
                ["enable"] = true,
                ["groupType"] = "group",
                ["excludeDispelTypes"] = {
                },
                ["excludeSpellIDs"] = "",
            },
            ["load"] = {
                ["loadRoles"] = {
                },
                ["loadSpecs"] = {
                },
                ["loadInstances"] = {
                },
                ["hasLoadConditions"] = false,
                ["onlyLoadOnPlayer"] = "",
                ["loadClasses"] = {
                },
                ["dontLoadOnPlayer"] = "",
            },
            ["visual"] = {
                ["durationColor"] = {
                    ["a"] = 1,
                    ["r"] = 1,
                    ["g"] = 1,
                    ["b"] = 1,
                },
                ["barIconPosition"] = "LEFT",
                ["durationFormat"] = "mmss",
                ["barHeight"] = 20,
                ["spellNameYOff"] = -2,
                ["stackRelativePoint"] = "TOPRIGHT",
                ["elementHeight"] = 0,
                ["elementWidth"] = 0,
                ["showStacks"] = true,
                ["iconWidth"] = 25,
                ["barTexture"] = "ExalityUI Status Bar",
                ["barColor"] = {
                    ["a"] = 1,
                    ["r"] = 0.2,
                    ["g"] = 0.6,
                    ["b"] = 1,
                },
                ["stackFontSize"] = 13,
                ["barBorderColor"] = {
                    ["a"] = 1,
                    ["r"] = 0,
                    ["g"] = 0,
                    ["b"] = 0,
                },
                ["slotRelativePoint"] = "CENTER",
                ["stackXOff"] = 0,
                ["slotAnchorPoint"] = "CENTER",
                ["slotYOff"] = 0,
                ["showDurationText"] = true,
                ["dispelBorderShowIcon"] = true,
                ["displayStyle"] = "icon",
                ["gapY"] = 0,
                ["durationExpiredText"] = "",
                ["barTimerDirection"] = "RemainingTime",
                ["barIconGap"] = 0,
                ["elementSpacingY"] = 2,
                ["gapX"] = 0,
                ["stackColor"] = {
                    ["a"] = 1,
                    ["r"] = 1,
                    ["g"] = 1,
                    ["b"] = 1,
                },
                ["spellNameFontSize"] = 10,
                ["forceNewRow"] = false,
                ["slotXOff"] = 0,
                ["dispelBorderStyle"] = "Atlas",
                ["stackAnchorPoint"] = "RIGHT",
                ["durationZeroText"] = "",
                ["showSpellName"] = false,
                ["durationFontFlag"] = "OUTLINE",
                ["spellNameAnchorPoint"] = "BOTTOM",
                ["dispelBorderHarmful"] = true,
                ["spellNameRelativePoint"] = "TOP",
                ["iconBorderThickness"] = 1,
                ["barBackgroundColor"] = {
                    ["a"] = 0.5,
                    ["r"] = 0,
                    ["g"] = 0,
                    ["b"] = 0,
                },
                ["durationFontSize"] = 12,
                ["showBarIcon"] = true,
                ["durationAnchorPoint"] = "BOTTOM",
                ["stackFontFlag"] = "OUTLINE",
                ["spellNameXOff"] = 0,
                ["stackYOff"] = 0,
                ["elementSpacingX"] = 1,
                ["showDurationCooldown"] = true,
                ["stackFont"] = "DMSans",
                ["spellNameFont"] = "DMSans",
                ["showIconBorder"] = true,
                ["durationRelativePoint"] = "BOTTOM",
                ["durationXOff"] = 0,
                ["showDispelBorder"] = false,
                ["iconBorderColor"] = {
                    ["a"] = 1,
                    ["r"] = 0,
                    ["g"] = 0,
                    ["b"] = 0,
                },
                ["iconHeight"] = 25,
                ["durationFont"] = "DMSans",
                ["durationYOff"] = 0,
                ["durationUpdateInterval"] = 0,
                ["iconZoom"] = 10,
                ["barBorderThickness"] = 1,
                ["spellNameFontFlag"] = "OUTLINE",
                ["spellNameColor"] = {
                    ["a"] = 1,
                    ["r"] = 1,
                    ["g"] = 1,
                    ["b"] = 1,
                },
                ["dispelBorderHelpful"] = false,
                ["barWidth"] = 160,
            },
        },
    },
    ["relativePoint"] = "BOTTOMRIGHT",
    ["paddingBottom"] = 0,
    ["container"] = {
        ["itemEnchantWidth"] = 0,
        ["itemEnchantPlacement"] = "BeforeAuraGroups",
        ["itemEnchantRanged"] = false,
        ["itemEnchantHidePermanent"] = false,
        ["itemEnchantSpacingX"] = 2,
        ["itemEnchantEnable"] = false,
        ["itemEnchantOffHand"] = false,
        ["itemEnchantGapY"] = 0,
        ["itemEnchantGapX"] = 0,
        ["processAuraOptions"] = {
            ["ignoreDebuffs"] = false,
            ["ignoreDispelDebuffs"] = false,
            ["displayOnlyDispellableDebuffs"] = false,
            ["ignoreBuffs"] = false,
        },
        ["itemEnchantMainHand"] = false,
        ["itemEnchantSpacingY"] = 2,
        ["itemEnchantHeight"] = 0,
    },
    ["paddingTop"] = 0,
    ["frameLevel"] = 10,
    ["matchUnitFrameWidth"] = true,
    ["frameStrata"] = "LOW",
    ["units"] = {
        ["target"] = true,
    },
    ["rowWidth"] = 189,
    ["verticalGrowth"] = "UP",
    ["name"] = "Debuffs - Right",
    ["groupOrder"] = {
        "1gyg5a6uJjVv",
    },
    ["paddingLeft"] = 0,
    ["YOff"] = 0,
    ["paddingRight"] = 0,
    ["XOff"] = 0,
},
["W3v7eSDr6T6s"] = {
    ["horizontalGrowth"] = "RIGHT",
    ["enable"] = true,
    ["containerAnchorPoint"] = "BOTTOMLEFT",
    ["anchorPoint"] = "BOTTOMLEFT",
    ["createdAt"] = 1784138822,
    ["groups"] = {
        ["AHphdkmYf0uB"] = {
            ["enable"] = true,
            ["conditions"] = {
                ["isPriorityAura"] = false,
                ["isBossAura"] = false,
                ["isStealable"] = false,
                ["isFromPlayerOrPlayerPet"] = false,
                ["isRoleAura"] = false,
                ["sortDirection"] = "Normal",
                ["filterTokens"] = {
                    {
                        ["token"] = "HELPFUL",
                        ["negated"] = false,
                    },
                    {
                        ["token"] = "IMPORTANT",
                        ["negated"] = false,
                    },
                },
                ["nameplateShowPersonal"] = false,
                ["nameplateShowAll"] = false,
                ["isBossOrRoleAura"] = false,
                ["includeSpellIDs"] = "",
                ["excludeSpellIDs"] = "",
                ["maxDuration"] = 0,
                ["includeDispelTypes"] = {
                },
                ["canApplyAura"] = false,
                ["sortMethod"] = "Default",
                ["enable"] = true,
                ["groupType"] = "group",
                ["excludeDispelTypes"] = {
                },
                ["maxFrameCount"] = 8,
            },
            ["load"] = {
                ["loadRoles"] = {
                },
                ["loadSpecs"] = {
                },
                ["loadInstances"] = {
                },
                ["hasLoadConditions"] = false,
                ["onlyLoadOnPlayer"] = "",
                ["loadClasses"] = {
                },
                ["dontLoadOnPlayer"] = "",
            },
            ["visual"] = {
                ["durationColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["barIconPosition"] = "LEFT",
                ["durationFormat"] = "mmss",
                ["barBorderThickness"] = 1,
                ["spellNameYOff"] = -2,
                ["stackRelativePoint"] = "TOPRIGHT",
                ["elementHeight"] = 0,
                ["elementWidth"] = 0,
                ["showStacks"] = true,
                ["iconWidth"] = 25,
                ["barTexture"] = "ExalityUI Status Bar",
                ["barColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 0.6,
                    ["r"] = 0.2,
                },
                ["stackFontSize"] = 13,
                ["barBorderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["slotRelativePoint"] = "CENTER",
                ["stackFont"] = "DMSans",
                ["slotAnchorPoint"] = "CENTER",
                ["slotYOff"] = 0,
                ["showDurationText"] = true,
                ["dispelBorderShowIcon"] = true,
                ["displayStyle"] = "icon",
                ["gapY"] = 0,
                ["durationExpiredText"] = "",
                ["barTimerDirection"] = "RemainingTime",
                ["barIconGap"] = 0,
                ["elementSpacingY"] = 2,
                ["gapX"] = 0,
                ["stackColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["spellNameFontSize"] = 10,
                ["durationYOff"] = 0,
                ["slotXOff"] = 0,
                ["dispelBorderStyle"] = "Atlas",
                ["stackAnchorPoint"] = "RIGHT",
                ["durationZeroText"] = "",
                ["showSpellName"] = false,
                ["durationFontFlag"] = "OUTLINE",
                ["spellNameAnchorPoint"] = "BOTTOM",
                ["dispelBorderHarmful"] = true,
                ["spellNameRelativePoint"] = "TOP",
                ["iconBorderThickness"] = 1,
                ["barBackgroundColor"] = {
                    ["a"] = 0.5,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["durationFontSize"] = 12,
                ["showBarIcon"] = true,
                ["durationAnchorPoint"] = "BOTTOM",
                ["stackFontFlag"] = "OUTLINE",
                ["spellNameXOff"] = 0,
                ["dispelBorderHelpful"] = false,
                ["spellNameColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["spellNameFontFlag"] = "OUTLINE",
                ["spellNameFont"] = "DMSans",
                ["showDurationCooldown"] = true,
                ["durationUpdateInterval"] = 0,
                ["iconHeight"] = 25,
                ["iconBorderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["showDispelBorder"] = false,
                ["durationXOff"] = 0,
                ["durationRelativePoint"] = "BOTTOM",
                ["durationFont"] = "DMSans",
                ["forceNewRow"] = false,
                ["showIconBorder"] = true,
                ["iconZoom"] = 10,
                ["barHeight"] = 20,
                ["stackXOff"] = 0,
                ["elementSpacingX"] = 1,
                ["stackYOff"] = 0,
                ["barWidth"] = 160,
            },
        },
    },
    ["relativePoint"] = "TOPLEFT",
    ["paddingBottom"] = 0,
    ["container"] = {
        ["itemEnchantWidth"] = 0,
        ["itemEnchantPlacement"] = "BeforeAuraGroups",
        ["itemEnchantRanged"] = false,
        ["itemEnchantHidePermanent"] = false,
        ["itemEnchantSpacingX"] = 2,
        ["itemEnchantHeight"] = 0,
        ["itemEnchantGapY"] = 0,
        ["itemEnchantOffHand"] = false,
        ["itemEnchantGapX"] = 0,
        ["processAuraOptions"] = {
            ["ignoreDebuffs"] = false,
            ["ignoreDispelDebuffs"] = false,
            ["displayOnlyDispellableDebuffs"] = false,
            ["ignoreBuffs"] = false,
        },
        ["itemEnchantMainHand"] = false,
        ["itemEnchantSpacingY"] = 2,
        ["itemEnchantEnable"] = false,
    },
    ["paddingTop"] = 0,
    ["frameLevel"] = 0,
    ["matchUnitFrameWidth"] = true,
    ["frameStrata"] = "BACKGROUND",
    ["units"] = {
        ["target"] = true,
    },
    ["rowWidth"] = 189,
    ["verticalGrowth"] = "UP",
    ["name"] = "Buffs - Above",
    ["XOff"] = 0,
    ["paddingRight"] = 0,
    ["YOff"] = 0,
    ["paddingLeft"] = 0,
    ["groupOrder"] = {
        "AHphdkmYf0uB",
    },
},
["YXm8naeAQvV1"] = {
    ["horizontalGrowth"] = "LEFT",
    ["enable"] = true,
    ["containerAnchorPoint"] = "TOPRIGHT",
    ["anchorPoint"] = "TOPRIGHT",
    ["createdAt"] = 1784146144,
    ["groups"] = {
        ["ocXigvykc3GU"] = {
            ["enable"] = true,
            ["conditions"] = {
                ["isPriorityAura"] = false,
                ["isBossAura"] = false,
                ["isStealable"] = false,
                ["isFromPlayerOrPlayerPet"] = false,
                ["isRoleAura"] = false,
                ["sortDirection"] = "Normal",
                ["filterTokens"] = {
                    {
                        ["token"] = "HELPFUL",
                        ["negated"] = false,
                    },
                    {
                        ["token"] = "BIG_DEFENSIVE",
                        ["negated"] = false,
                    },
                },
                ["nameplateShowPersonal"] = false,
                ["nameplateShowAll"] = false,
                ["isBossOrRoleAura"] = false,
                ["includeSpellIDs"] = "",
                ["excludeSpellIDs"] = "",
                ["maxDuration"] = 0,
                ["includeDispelTypes"] = {
                },
                ["canApplyAura"] = false,
                ["sortMethod"] = "Default",
                ["enable"] = true,
                ["groupType"] = "group",
                ["excludeDispelTypes"] = {
                },
                ["maxFrameCount"] = 3,
            },
            ["load"] = {
                ["loadRoles"] = {
                    "Healer",
                },
                ["loadSpecs"] = {
                },
                ["loadInstances"] = {
                },
                ["hasLoadConditions"] = true,
                ["onlyLoadOnPlayer"] = "",
                ["loadClasses"] = {
                },
                ["dontLoadOnPlayer"] = "",
            },
            ["visual"] = {
                ["durationColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["barIconPosition"] = "LEFT",
                ["durationFormat"] = "mmss",
                ["barBorderThickness"] = 1,
                ["spellNameYOff"] = -2,
                ["stackRelativePoint"] = "TOPRIGHT",
                ["elementHeight"] = 0,
                ["elementWidth"] = 0,
                ["showStacks"] = true,
                ["iconWidth"] = 25,
                ["barTexture"] = "ExalityUI Status Bar",
                ["barColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 0.6,
                    ["r"] = 0.2,
                },
                ["stackFontSize"] = 14,
                ["barBorderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["slotRelativePoint"] = "CENTER",
                ["stackFont"] = "DMSans",
                ["slotAnchorPoint"] = "CENTER",
                ["slotYOff"] = 0,
                ["showDurationText"] = true,
                ["dispelBorderShowIcon"] = true,
                ["displayStyle"] = "icon",
                ["gapY"] = 0,
                ["durationExpiredText"] = "",
                ["barTimerDirection"] = "RemainingTime",
                ["barIconGap"] = 0,
                ["elementSpacingY"] = 2,
                ["gapX"] = 0,
                ["stackColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["spellNameFontSize"] = 10,
                ["durationYOff"] = 0,
                ["slotXOff"] = 0,
                ["dispelBorderStyle"] = "Atlas",
                ["stackAnchorPoint"] = "CENTER",
                ["durationZeroText"] = "",
                ["showSpellName"] = false,
                ["durationFontFlag"] = "OUTLINE",
                ["spellNameAnchorPoint"] = "BOTTOM",
                ["dispelBorderHarmful"] = true,
                ["spellNameRelativePoint"] = "TOP",
                ["iconBorderThickness"] = 1,
                ["barBackgroundColor"] = {
                    ["a"] = 0.5,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["durationFontSize"] = 12,
                ["showBarIcon"] = true,
                ["durationAnchorPoint"] = "CENTER",
                ["stackFontFlag"] = "OUTLINE",
                ["spellNameXOff"] = 0,
                ["dispelBorderHelpful"] = false,
                ["spellNameColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["spellNameFontFlag"] = "OUTLINE",
                ["spellNameFont"] = "DMSans",
                ["showDurationCooldown"] = true,
                ["durationUpdateInterval"] = 0,
                ["iconHeight"] = 25,
                ["iconBorderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["showDispelBorder"] = true,
                ["durationXOff"] = 0,
                ["durationRelativePoint"] = "BOTTOM",
                ["durationFont"] = "DMSans",
                ["forceNewRow"] = false,
                ["showIconBorder"] = true,
                ["iconZoom"] = 16,
                ["barHeight"] = 20,
                ["stackXOff"] = -2,
                ["elementSpacingX"] = 2,
                ["stackYOff"] = -2,
                ["barWidth"] = 160,
            },
        },
    },
    ["relativePoint"] = "TOPRIGHT",
    ["paddingBottom"] = 0,
    ["container"] = {
        ["itemEnchantWidth"] = 0,
        ["itemEnchantPlacement"] = "BeforeAuraGroups",
        ["itemEnchantRanged"] = false,
        ["itemEnchantHidePermanent"] = false,
        ["itemEnchantSpacingX"] = 2,
        ["itemEnchantHeight"] = 0,
        ["itemEnchantGapY"] = 0,
        ["itemEnchantOffHand"] = false,
        ["itemEnchantGapX"] = 0,
        ["processAuraOptions"] = {
            ["ignoreDebuffs"] = false,
            ["ignoreDispelDebuffs"] = false,
            ["displayOnlyDispellableDebuffs"] = false,
            ["ignoreBuffs"] = false,
        },
        ["itemEnchantMainHand"] = false,
        ["itemEnchantSpacingY"] = 2,
        ["itemEnchantEnable"] = false,
    },
    ["paddingTop"] = 0,
    ["frameLevel"] = 10,
    ["matchUnitFrameWidth"] = true,
    ["frameStrata"] = "HIGH",
    ["units"] = {
        ["party"] = true,
        ["raid"] = true,
    },
    ["rowWidth"] = 200,
    ["verticalGrowth"] = "UP",
    ["name"] = "DRs (Load = Healers)",
    ["XOff"] = -2,
    ["paddingRight"] = 0,
    ["YOff"] = -1,
    ["paddingLeft"] = 0,
    ["groupOrder"] = {
        "ocXigvykc3GU",
    },
},
["9YIOZS0DNXEy"] = {
    ["horizontalGrowth"] = "RIGHT",
    ["enable"] = true,
    ["containerAnchorPoint"] = "BOTTOMLEFT",
    ["anchorPoint"] = "BOTTOMLEFT",
    ["createdAt"] = 1784216384,
    ["groups"] = {
        ["vKEekrXcJm9t"] = {
            ["enable"] = true,
            ["conditions"] = {
                ["isPriorityAura"] = false,
                ["isBossAura"] = false,
                ["isStealable"] = false,
                ["isFromPlayerOrPlayerPet"] = false,
                ["isRoleAura"] = false,
                ["sortDirection"] = "Normal",
                ["filterTokens"] = {
                    {
                        ["token"] = "HARMFUL",
                        ["negated"] = false,
                    },
                    {
                        ["token"] = "IMPORTANT",
                        ["negated"] = false,
                    },
                },
                ["nameplateShowPersonal"] = false,
                ["nameplateShowAll"] = false,
                ["isBossOrRoleAura"] = false,
                ["includeSpellIDs"] = "",
                ["excludeSpellIDs"] = "",
                ["maxDuration"] = 0,
                ["includeDispelTypes"] = {
                },
                ["canApplyAura"] = false,
                ["sortMethod"] = "Default",
                ["enable"] = true,
                ["groupType"] = "group",
                ["excludeDispelTypes"] = {
                },
                ["maxFrameCount"] = 10,
            },
            ["load"] = {
                ["loadRoles"] = {
                },
                ["loadSpecs"] = {
                },
                ["loadInstances"] = {
                },
                ["hasLoadConditions"] = false,
                ["onlyLoadOnPlayer"] = "",
                ["loadClasses"] = {
                },
                ["dontLoadOnPlayer"] = "",
            },
            ["visual"] = {
                ["durationColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["barIconPosition"] = "LEFT",
                ["durationFormat"] = "mmss",
                ["barBorderThickness"] = 1,
                ["spellNameYOff"] = -2,
                ["stackRelativePoint"] = "TOPRIGHT",
                ["elementHeight"] = 0,
                ["elementWidth"] = 0,
                ["showStacks"] = true,
                ["iconWidth"] = 25,
                ["barTexture"] = "ExalityUI Status Bar",
                ["barColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 0.6,
                    ["r"] = 0.2,
                },
                ["stackFontSize"] = 13,
                ["barBorderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["slotRelativePoint"] = "CENTER",
                ["stackXOff"] = 0,
                ["slotAnchorPoint"] = "CENTER",
                ["slotYOff"] = 0,
                ["showDurationText"] = true,
                ["dispelBorderShowIcon"] = true,
                ["displayStyle"] = "icon",
                ["gapY"] = 0,
                ["durationExpiredText"] = "",
                ["barTimerDirection"] = "RemainingTime",
                ["barIconGap"] = 0,
                ["elementSpacingY"] = 2,
                ["gapX"] = 0,
                ["stackColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["spellNameFontSize"] = 10,
                ["durationYOff"] = 0,
                ["slotXOff"] = 0,
                ["dispelBorderStyle"] = "Atlas",
                ["stackAnchorPoint"] = "RIGHT",
                ["durationZeroText"] = "",
                ["showSpellName"] = false,
                ["durationFontFlag"] = "OUTLINE",
                ["spellNameAnchorPoint"] = "BOTTOM",
                ["spellNameFontFlag"] = "OUTLINE",
                ["spellNameRelativePoint"] = "TOP",
                ["iconBorderThickness"] = 1,
                ["barBackgroundColor"] = {
                    ["a"] = 0.5,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["durationFontSize"] = 12,
                ["showBarIcon"] = true,
                ["durationAnchorPoint"] = "BOTTOM",
                ["stackFontFlag"] = "OUTLINE",
                ["spellNameXOff"] = 0,
                ["dispelBorderHelpful"] = false,
                ["spellNameColor"] = {
                    ["a"] = 1,
                    ["b"] = 1,
                    ["g"] = 1,
                    ["r"] = 1,
                },
                ["spellNameFont"] = "DMSans",
                ["durationFont"] = "DMSans",
                ["stackFont"] = "DMSans",
                ["durationUpdateInterval"] = 0,
                ["iconHeight"] = 25,
                ["iconBorderColor"] = {
                    ["a"] = 1,
                    ["b"] = 0,
                    ["g"] = 0,
                    ["r"] = 0,
                },
                ["showDispelBorder"] = false,
                ["durationXOff"] = 0,
                ["durationRelativePoint"] = "BOTTOM",
                ["dispelBorderHarmful"] = true,
                ["forceNewRow"] = false,
                ["showIconBorder"] = true,
                ["iconZoom"] = 10,
                ["barHeight"] = 20,
                ["showDurationCooldown"] = true,
                ["elementSpacingX"] = 1,
                ["stackYOff"] = 0,
                ["barWidth"] = 160,
            },
        },
    },
    ["relativePoint"] = "TOPLEFT",
    ["paddingBottom"] = 0,
    ["container"] = {
        ["itemEnchantHeight"] = 0,
        ["itemEnchantPlacement"] = "BeforeAuraGroups",
        ["itemEnchantRanged"] = false,
        ["itemEnchantHidePermanent"] = false,
        ["itemEnchantSpacingX"] = 2,
        ["itemEnchantGapY"] = 0,
        ["itemEnchantEnable"] = false,
        ["itemEnchantOffHand"] = false,
        ["itemEnchantGapX"] = 0,
        ["processAuraOptions"] = {
            ["ignoreDebuffs"] = false,
            ["ignoreDispelDebuffs"] = false,
            ["displayOnlyDispellableDebuffs"] = false,
            ["ignoreBuffs"] = false,
        },
        ["itemEnchantMainHand"] = false,
        ["itemEnchantSpacingY"] = 2,
        ["itemEnchantWidth"] = 0,
    },
    ["paddingTop"] = 0,
    ["frameLevel"] = 10,
    ["matchUnitFrameWidth"] = true,
    ["frameStrata"] = "LOW",
    ["units"] = {
        ["focus"] = true,
    },
    ["rowWidth"] = 189,
    ["verticalGrowth"] = "UP",
    ["name"] = "Important Debuffs",
    ["XOff"] = 0,
    ["paddingRight"] = 0,
    ["YOff"] = 0,
    ["paddingLeft"] = 0,
    ["groupOrder"] = {
        "vKEekrXcJm9t",
    },
},
}

function defaults:SeedStarterDisplays(db)
    if not db or db.__exuiStarterDisplaysSeeded then
        return false
    end
    db.displays = db.displays or {}
    for displayID, display in pairs(self.STARTER_DISPLAYS) do
        if not db.displays[displayID] then
            db.displays[displayID] = self:CopyTable(display)
        end
    end
    db.__exuiStarterDisplaysSeeded = true
    return true
end
